---
author: Logan McDonald <logan@kickstarter.com>
cog_bundle_version: 4
name: consul
description: Wrapper for Consul, a key value secret keeper.
version: 1.0.22
docker:
  image: "kickstarter/cog-consul-oss"
  tag: 'v1.0.22'
commands:
  read:
    executable: /home/bundle/cog-command
    description: Get values for a given key
    arguments: "<key>"
    rules:
      - 'allow'
  write:
    executable: /home/bundle/cog-command
    description: Write the value for a given key
    arguments: "<key> <value>"
    rules:
      - 'allow'
  list:
    executable: /home/bundle/cog-command
    description: List given keys for an endpoint
    arguments: "<endpoint>"
    rules:
      - 'allow'
templates:
  default:
    body: |
      ```
      ~$results[0].body~
      ```
